import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ContentLayout } from "@/components/bharatkhoj/ContentLayout";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
const description = "Customize language, safe search, suggestions, and result preferences for BharatKhoj.";
export const Route = createFileRoute("/settings")({ head: () => ({ meta: [{ title: "Search Preferences — BharatKhoj" }, { name: "description", content: description }, { property: "og:title", content: "Search Preferences — BharatKhoj" }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { property: "og:url", content: "/settings" }, { name: "twitter:card", content: "summary" }], links: [{ rel: "canonical", href: "/settings" }] }), component: SettingsPage });
function SettingsPage() { const [saved, setSaved] = useState(false); return <ContentLayout title="Search preferences" intro="Choose how BharatKhoj presents your search experience."><form className="settings-form" onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><Setting label="Language" hint="Language used in BharatKhoj controls"><Select defaultValue="english"><SelectTrigger aria-label="Language"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="english">English</SelectItem><SelectItem value="hindi">हिन्दी</SelectItem><SelectItem value="bengali">বাংলা</SelectItem><SelectItem value="tamil">தமிழ்</SelectItem></SelectContent></Select></Setting><Setting label="Safe search" hint="Filter explicit content"><Switch defaultChecked aria-label="Safe search" /></Setting><Setting label="Search suggestions" hint="Show provider suggestions while typing"><Switch defaultChecked aria-label="Search suggestions" /></Setting><Setting label="Results per page" hint="Number of organic results"><Select defaultValue="10"><SelectTrigger aria-label="Results per page"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="10">10 results</SelectItem><SelectItem value="20">20 results</SelectItem></SelectContent></Select></Setting><Button type="submit">Save settings</Button>{saved && <p className="form-success" role="status">Your preferences have been saved for this visit.</p>}</form></ContentLayout>; }
function Setting({ label, hint, children }: { label: string; hint: string; children: React.ReactNode }) { return <div className="setting-row"><span><strong>{label}</strong><small>{hint}</small></span><div>{children}</div></div>; }
