/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSuggestionsRouteImport } from './routes/api/suggestions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestionsRoute = ApiSuggestionsRouteImport.update({
  id: '/api/suggestions',
  path: '/api/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/search' | '/api/suggestions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/search' | '/api/suggestions'
  id: '__root__' | '/' | '/api/search' | '/api/suggestions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSuggestionsRoute: typeof ApiSuggestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggestions': {
      id: '/api/suggestions'
      path: '/api/suggestions'
      fullPath: '/api/suggestions'
      preLoaderRoute: typeof ApiSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSuggestionsRoute: ApiSuggestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
